[workspace]
members = ["crates/hangar-core", "crates/hangar-app"]
resolver = "2"

[workspace.package]
version = "0.4.1"
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.91"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
panic = "abort"
