[target.i686-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-C", "link-arg=/ENTRY:mainCRTStartup", "-C", "link-arg=/SUBSYSTEM:WINDOWS,4.0", "-C", "link-arg=/OSVERSION:4.0", "-C", "link-arg=/NODEFAULTLIB", "-C", "link-arg=/SAFESEH:NO", "-C", "link-arg=/DYNAMICBASE:NO", "-C", "link-arg=/NXCOMPAT:NO"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-C", "link-arg=/ENTRY:mainCRTStartup", "-C", "link-arg=/SUBSYSTEM:WINDOWS,6.0", "-C", "link-arg=/NODEFAULTLIB"]
